### ISSUE TITLE
Postgres Support with Rabbit MQ or Kafka

### ISSUE THREAD

**Issue by missulmer** [Senzing/risk-score-calculator#12]
[Specific customer request 3180]

Given that a customer wants to use the risk-score-calculator and are moving to use of the postgres db for their Sz adoption, the risk-score-calculator must support Postgres db.

Given that the same customer also is moving from using g2loader to the stream producer and would like to adopt either rabbitMQ or Kafka for their data pipelines for either historicals and ongoing feeds, ensure that the risk-score-calculator works with both pub-sub and producer/consumer stream processor.

**Comment by oskar700** [comment]
It already works with Postgres and Rabbit MQ producer/consumer.  I will add sub-pub functionality.

**Comment by oskar700** [comment]
The connection can be set in the "conf/risk-scoring-calculator.properties" file.  The parameter is "riskscorer.jdbc.connection" and is a jdbc connection string:
riskscorer.jdbc.connection=jdbc:postgresql://host:port/database

**Comment by missulmer** [comment]
Thank you :)

**Comment by missulmer** [comment]
This item will be covered in AR meeting with the requesting customer this month.
