### ISSUE TITLE
Enhancement Request: Reason Deduplication 

### ISSUE THREAD

**Issue by missulmer** [Senzing/risk-score-calculator#13]
Dedupe the query reason data, so only one instance of match key appears per match key type so instead of +NAME+DOB, +NAME+DOB, +NAME+ADDRESS it should be +NAME+DOB, +NAME+ADDRESS

Given that a developer is looking at reason data, and wants uncluttered reasons, is it possible to remove what appear to be duplicate reasons?

If there is a reason for the apparent duplication of match keys in reason data, can this be explained and documented in the project?

**Comment by oskar700** [comment]
This has been fixed with https://github.com/Senzing/risk-score-calculator/pull/15
