### ISSUE TITLE
Could not resolve dependencies for project com.senzing:risk-scoring-calculator:jar:0.0.1-SNAPSHOT: Could not find artifact com.senzing:senzing-listener:jar:0.0.1-SNAPSHO

### ISSUE THREAD

**Issue by Ashish3013** [Senzing/risk-score-calculator#27]
uba@ubuntu:~/.m2/repository/com/senzing/g2$ mvn -f /home/uba/risk-score-calculator/pom.xml install
[INFO] Scanning for projects...
[INFO] 
[INFO] ----------------< com.senzing:risk-scoring-calculator >-----------------
[INFO] Building G2 Risk Scoring Calculator 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for com.senzing:senzing-listener:jar:0.0.1-SNAPSHOT is missing, no dependency information available
[WARNING] The artifact org.apache.commons:commons-io:jar:1.3.2 has been relocated to commons-io:commons-io:jar:1.3.2: https://issues.sonatype.org/browse/MVNCENTRAL-244
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.620 s
[INFO] Finished at: 2022-01-02T11:15:25-08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project risk-scoring-calculator: Could not resolve dependencies for project com.senzing:risk-scoring-calculator:jar:0.0.1-SNAPSHOT: Could not find artifact com.senzing:senzing-listener:jar:0.0.1-SNAPSHOT -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by oskar700** [comment]
This is the same as https://github.com/Senzing/risk-score-calculator/issues/23.  There is a workaround in the description of that issue.

**Comment by oskar700** [comment]
Are you satisfied with the solution to this issue?  If so, please close as being completed.
If we don't hear back from you we will close this in 5 days.
